name: checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1

  pyright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        cache: 'pip'
    - run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - run: echo "$PWD/venv/bin" >> $GITHUB_PATH
    - uses: jakebailey/pyright-action@v2

  otree:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - run: echo "$PWD/venv/bin" >> $GITHUB_PATH
    - run: otree test
